stages:
  - lint
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CUSTOM_CI_IMAGE: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG

.nix_build_template:
  interruptible: true
  variables:
    PYTHONUNBUFFERED: "1"
    TERM: "xterm"
  rules:
    - when: always
  tags:
    - native-nix-v2
  before_script:
    - git config --global --add url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/.insteadOf "git@${CI_SERVER_HOST}:"
    - git config --global --add url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/.insteadOf "ssh://git@${CI_SERVER_HOST}/"
    - unset NIX_PATH
    - export TMPDIR=$(mktemp -d) # randomize tmp dir to prevent clashes of nixos tests
    # We experience CI weirdness with our runners: sometimes we see orphaned
    # QEMU processes still running and blocking host ports, thus, the CI will
    # fail.
    #
    # On the long term, we should refactor the tests to export all tests in CI
    # mode and interactive mode where only the latter also binds the host
    # ports. This here, however, is the more pragmatic workaround for now.
    - |
      echo "Checking if any orphaned QEMU process needs to be killed ..."

      kill_qemu() {
        local port=$1
        local pid=$(nix shell nixpkgs#procps --command bash -c "pgrep -f 'qemu.*[h]ostfwd=tcp::$port' || echo -1")
        if [ "${pid}" -gt 1 ]; then
          nix shell nixpkgs#ansi --command bash -c "echo -e \"\$(ansi red bold)FOUND ORPHANED QEMU (pid=$pid) blocking port $port: Killing to unblock pipeline\$(ansi reset)\""
          kill -KILL "${pid}"
        fi
      }

      kill_qemu 6083
      kill_qemu 8080

lint:linter:
  stage: lint
  extends:
    - .nix_build_template
  dependencies: []
  script:
    - nix build -L .#checks.x86_64-linux.default

lint:gitlint:
  variables:
    GIT_STRATEGY: "clone"   # Forces full clone instead of fetch
    GIT_DEPTH: 0            # Disables shallow clone (full history)
  stage: lint
  rules:
      # Needed for TARGET_BRANCH below.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never
  extends:
    - .nix_build_template
  dependencies: []
  script:
    # Determine the target branch of the merge request
    - TARGET_BRANCH=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-$CI_DEFAULT_BRANCH}
    - echo "TARGET_BRANCH=$TARGET_BRANCH"
    - nix run nixpkgs#gitlint -- --commits origin/gardenlinux..

test:basic-test:
  stage: test
  needs: []
  extends:
    - .nix_build_template
  dependencies: []
  script:
    - nix build .#tests.x86_64-linux.nova-chv-driver.driver
    - nix run .#tests.x86_64-linux.nova-chv-driver.driver

test:live-migration-test:
  stage: test
  needs: [ "test:basic-test" ]
  extends:
    - .nix_build_template
  dependencies: []
  script:
    - nix build .#tests.x86_64-linux.chv-live-migration.driver
    - nix run .#tests.x86_64-linux.chv-live-migration.driver

test:hugepage-numa-test:
  stage: test
  needs: [ "test:live-migration-test" ]
  extends:
    - .nix_build_template
  dependencies: []
  script:
    - nix build .#tests.x86_64-linux.chv-numa.driver
    - nix run .#tests.x86_64-linux.chv-numa.driver

test:bdf-live-migration-test:
  stage: test
  needs: [ "test:hugepage-numa-test" ]
  extends:
    - .nix_build_template
  dependencies: []
  script:
    - nix build .#tests.x86_64-linux.chv-bdf-live-migration.driver
    - nix run .#tests.x86_64-linux.chv-bdf-live-migration.driver
